version: "3.8"

services:

  postgres:
    image: postgres:12.5-alpine
    environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks: 
      - keycloak_network
    container_name: postgres_container

  keycloak:
    image: jboss/keycloak:12.0.2
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      DB_ADDR: postgres
    ports:
      - 8080:8080
    networks: 
      - keycloak_network
    depends_on: 
      - postgres
    container_name: keycloak_container

volumes:
  postgres_data:
    name: postgres_data

networks:
  keycloak_network:
    name: keycloak_network
    driver: bridge
