version: "3.8"

services:

  db:
    image: postgres:12.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: robson
      POSTGRES_USER: robson
      POSTGRES_DB: mydb
    ports:
      - 15432:5432
    volumes:
      - data:/var/lib/postgresql/data
    container_name: postgres_mydb

volumes:
  data:
    name: postgres_mydb