version: "3.8"

services:

  mysql:
    image: mysql:8.0.23
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql    
    container_name: mysql-container

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
    ports:
      - 8081:80
    container_name: phpmyadmin-container

volumes:
  mysql-data: